
version: 2

models:
  - name: 'money_supply'
    description: "money_supply"
    columns:
      - name: Year
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: M2 Money and Quasi-Money
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: M1 Money
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: M0 Currency in Circulation
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: data_file_name
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: Ingestion_dt
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null