dbt_pboc:
  outputs:
    dev: 
      dbname: research_db_v1
      host: postgres
      pass: ${POSTGRES_PASSWORD}
      user: ${POSTGRES_USER}
      port: 5432
      schema: land
      threads: 1
      type: postgres
  target: dev
